"""Updated QuizQuestion model

Revision ID: 82ef70c50490
Revises: a4edab787a30
Create Date: 2024-11-03 19:11:38.682448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '82ef70c50490'
down_revision = 'a4edab787a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_quiz_result')
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.alter_column('user_answers',
               existing_type=sqlite.JSON(),
               nullable=False, 
               server_default='{}')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.alter_column('user_answers',
               existing_type=sqlite.JSON(),
               nullable=True)

    op.create_table('_alembic_tmp_quiz_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('user_answers', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
