"""Updated QuizResult model

Revision ID: a4edab787a30
Revises: db2d34d7109d
Create Date: 2024-11-03 17:40:20.280670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4edab787a30'
down_revision = 'db2d34d7109d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answers', sa.JSON(), nullable=True, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('user_answers')

    # ### end Alembic commands ###
