"""Updated QuizResult model

Revision ID: bf5306167699
Revises: 82ef70c50490
Create Date: 2024-11-03 21:35:55.693475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5306167699'
down_revision = '82ef70c50490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_ids', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('question_ids')

    # ### end Alembic commands ###
